spring.application.name=flightBookingSystem

# SQL showing and formatting
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true

# Spring banner off
spring.main.banner-mode=off

# Reducing logging level
logging.level.root = warn

# Giving permission to dev-application file
spring.profiles.active=dev
